const heroes = [
    {
      id: '1',
      name: 'Arcane Mage',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'arcane-mage-image-url',
      comments: [],
    },
    {
      id: '2',
      name: 'Knight',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'knight-image-url',
      comments: [],
    },
    {
      id: '3',
      name: 'Dark Ranger',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'dark-ranger-image-url',
      comments: [],
    },
    {
      id: '4',
      name: 'Crazy Tinkerer',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'crazy-tinkerer-image-url',
      comments: [],
    },
    {
      id: '5',
      name: 'Fire Wizard',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'fire-wizard-image-url',
      comments: [],
    },
    {
      id: '6',
      name: 'Frost Wizard',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'frost-wizard-image-url',
      comments: [],
    },
    {
      id: '7',
      name: 'Blademaster',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'blademaster-image-url',
      comments: [],
    },
    {
      id: '8',
      name: 'Spirit Shaman',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'spirit-shaman-image-url',
      comments: [],
    },
    {
      id: '9',
      name: 'Paladin',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'paladin-image-url',
      comments: [],
    },
    {
      id: '10',
      name: 'Reaper',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'reaper-image-url',
      comments: [],
    },
    {
      id: '11',
      name: 'Pirate Queen',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'pirate-queen-image-url',
      comments: [],
    },
    {
      id: '12',
      name: 'Warlock',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'warlock-image-url',
      comments: [],
    },
    {
      id: '13',
      name: 'Barbarian',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'barbarian-image-url',
      comments: [],
    },
    {
      id: '14',
      name: 'Big Game Hunter',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'big-game-hunter-image-url',
      comments: [],
    },
    {
      id: '15',
      name: 'Clockwork Mage',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'clockwork-mage-image-url',
      comments: [],
    },
    {
      id: '16',
      name: 'Monk',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'monk-image-url',
      comments: [],
    },
    {
      id: '17',
      name: 'Tide Warden',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'tide-warden-image-url',
      comments: [],
    },
    {
      id: '18',
      name: 'Assassin',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'assassin-image-url',
      comments: [],
    },
    {
      id: '19',
      name: 'Santa Clause',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'santa-clause-image-url',
      comments: [],
    },
    {
      id: '20',
      name: 'Frost Queen',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'frost-queen-image-url',
      comments: [],
    },
    {
      id: '21',
      name: 'Oracle',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'oracle-image-url',
      comments: [],
    },
    {
      id: '22',
      name: 'Dragon Empress',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'dragon-empress-image-url',
      comments: [],
    },
    {
      id: '23',
      name: 'Artificer',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'artificer-image-url',
      comments: [],
    },
    {
      id: '24',
      name: 'Dark Paladin',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'dark-paladin-image-url',
      comments: [],
    },
    {
      id: '25',
      name: 'Rocket Pilot',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'rocket-pilot-image-url',
      comments: [],
    },
    {
      id: '26',
      name: 'Leprechaun',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'leprechaun-image-url',
      comments: [],
    },
    {
      id: '27',
      name: 'Rose Mother',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'rose-mother-image-url',
      comments: [],
    },
    {
      id: '28',
      name: 'Bunni',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'bunni-image-url',
      comments: [],
    },
    {
      id: '29',
      name: 'Warlord',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'warlord-image-url',
      comments: [],
    },
    {
      id: '30',
      name: 'Hoplite',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'hoplite-image-url',
      comments: [],
    },
    {
      id: '31',
      name: 'Druid',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'druid-image-url',
      comments: [],
    },
    {
      id: '32',
      name: 'Necromancer',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'necromancer-image-url',
      comments: [],
    },
    {
      id: '33',
      name: 'Geomancer',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'geomancer-image-url',
      comments: [],
    },
    {
      id: '34',
      name: 'Energy Mage',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'energy-mage-image-url',
      comments: [],
    },
    {
      id: '35',
      name: 'Sentry Specialist',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'sentry-specialist-image-url',
      comments: [],
    },
    {
      id: '36',
      name: 'Werebeast',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'werebeast-image-url',
      comments: [],
    },
    {
      id: '37',
      name: 'Astral Mage',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'astral-mage-image-url',
      comments: [],
    },
    {
      id: '38',
      name: 'Void Raven',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'void-raven-image-url',
      comments: [],
    },
    {
      id: '39',
      name: 'Shield Warden',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'shield-warden-image-url',
      comments: [],
    },
    {
      id: '40',
      name: 'Scroll Mage',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'scroll-mage-image-url',
      comments: [],
    },
    {
      id: '41',
      name: 'Lionheart',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'lionheart-image-url',
      comments: [],
    },
    {
      id: '42',
      name: 'Steam Golem',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'steam-golem-image-url',
      comments: [],
    },
    {
      id: '43',
      name: 'Bavarian',
      level: 1,
      health: 100,
      attack: 10,
      defense: 5,
      image: 'bavarian-image-url',
      comments: [],
    },
  ];
  
  module.exports = heroes;